//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteExcelDna.RAE.WCF.Funcionario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionarioModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class FuncionarioModel : TesteExcelDna.RAE.WCF.Funcionario.PessoaFisicaModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SituacaoFuncionarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chapa {
            get {
                return this.ChapaField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapaField, value) != true)) {
                    this.ChapaField = value;
                    this.RaisePropertyChanged("Chapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funcao {
            get {
                return this.FuncaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoField, value) != true)) {
                    this.FuncaoField = value;
                    this.RaisePropertyChanged("Funcao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SituacaoFuncionario {
            get {
                return this.SituacaoFuncionarioField;
            }
            set {
                if ((this.SituacaoFuncionarioField.Equals(value) != true)) {
                    this.SituacaoFuncionarioField = value;
                    this.RaisePropertyChanged("SituacaoFuncionario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.PessoaFisicaModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel))]
    public partial class PessoaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeEstrangeiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataAtualizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteExcelDna.RAE.WCF.Funcionario.EnderecoModel EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnderecoEstrangeiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustificativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneComplementarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFEstrangeiroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CidadeEstrangeiro {
            get {
                return this.CidadeEstrangeiroField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeEstrangeiroField, value) != true)) {
                    this.CidadeEstrangeiroField = value;
                    this.RaisePropertyChanged("CidadeEstrangeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAtualizacao {
            get {
                return this.DataAtualizacaoField;
            }
            set {
                if ((this.DataAtualizacaoField.Equals(value) != true)) {
                    this.DataAtualizacaoField = value;
                    this.RaisePropertyChanged("DataAtualizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteExcelDna.RAE.WCF.Funcionario.EnderecoModel Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnderecoEstrangeiro {
            get {
                return this.EnderecoEstrangeiroField;
            }
            set {
                if ((this.EnderecoEstrangeiroField.Equals(value) != true)) {
                    this.EnderecoEstrangeiroField = value;
                    this.RaisePropertyChanged("EnderecoEstrangeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPessoa {
            get {
                return this.IdPessoaField;
            }
            set {
                if ((this.IdPessoaField.Equals(value) != true)) {
                    this.IdPessoaField = value;
                    this.RaisePropertyChanged("IdPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSituacao {
            get {
                return this.IdSituacaoField;
            }
            set {
                if ((this.IdSituacaoField.Equals(value) != true)) {
                    this.IdSituacaoField = value;
                    this.RaisePropertyChanged("IdSituacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Justificativa {
            get {
                return this.JustificativaField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificativaField, value) != true)) {
                    this.JustificativaField = value;
                    this.RaisePropertyChanged("Justificativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneComplementar {
            get {
                return this.TelefoneComplementarField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneComplementarField, value) != true)) {
                    this.TelefoneComplementarField = value;
                    this.RaisePropertyChanged("TelefoneComplementar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UFEstrangeiro {
            get {
                return this.UFEstrangeiroField;
            }
            set {
                if ((object.ReferenceEquals(this.UFEstrangeiroField, value) != true)) {
                    this.UFEstrangeiroField = value;
                    this.RaisePropertyChanged("UFEstrangeiro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class EnderecoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstrangeiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estrangeiro {
            get {
                return this.EstrangeiroField;
            }
            set {
                if ((this.EstrangeiroField.Equals(value) != true)) {
                    this.EstrangeiroField = value;
                    this.RaisePropertyChanged("Estrangeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogradouroTipo {
            get {
                return this.LogradouroTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroTipoField, value) != true)) {
                    this.LogradouroTipoField = value;
                    this.RaisePropertyChanged("LogradouroTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaFisicaModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel))]
    public partial class PessoaFisicaModel : TesteExcelDna.RAE.WCF.Funcionario.PessoaModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] DeficienciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoEstrangeiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdDocumentoEstrangeiroTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEscolaridadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdLocalErField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdLocalPaPaeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdResponsavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteExcelDna.RAE.WCF.Funcionario.PessoaFisicaModel.PjVinculadaModel[] PessoasJuridicasVinculadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SemEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SexoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Deficiencias {
            get {
                return this.DeficienciasField;
            }
            set {
                if ((object.ReferenceEquals(this.DeficienciasField, value) != true)) {
                    this.DeficienciasField = value;
                    this.RaisePropertyChanged("Deficiencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoEstrangeiro {
            get {
                return this.DocumentoEstrangeiroField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoEstrangeiroField, value) != true)) {
                    this.DocumentoEstrangeiroField = value;
                    this.RaisePropertyChanged("DocumentoEstrangeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdDocumentoEstrangeiroTipo {
            get {
                return this.IdDocumentoEstrangeiroTipoField;
            }
            set {
                if ((this.IdDocumentoEstrangeiroTipoField.Equals(value) != true)) {
                    this.IdDocumentoEstrangeiroTipoField = value;
                    this.RaisePropertyChanged("IdDocumentoEstrangeiroTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEscolaridade {
            get {
                return this.IdEscolaridadeField;
            }
            set {
                if ((this.IdEscolaridadeField.Equals(value) != true)) {
                    this.IdEscolaridadeField = value;
                    this.RaisePropertyChanged("IdEscolaridade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdLocalEr {
            get {
                return this.IdLocalErField;
            }
            set {
                if ((this.IdLocalErField.Equals(value) != true)) {
                    this.IdLocalErField = value;
                    this.RaisePropertyChanged("IdLocalEr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdLocalPaPae {
            get {
                return this.IdLocalPaPaeField;
            }
            set {
                if ((this.IdLocalPaPaeField.Equals(value) != true)) {
                    this.IdLocalPaPaeField = value;
                    this.RaisePropertyChanged("IdLocalPaPae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdResponsavel {
            get {
                return this.IdResponsavelField;
            }
            set {
                if ((this.IdResponsavelField.Equals(value) != true)) {
                    this.IdResponsavelField = value;
                    this.RaisePropertyChanged("IdResponsavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteExcelDna.RAE.WCF.Funcionario.PessoaFisicaModel.PjVinculadaModel[] PessoasJuridicasVinculadas {
            get {
                return this.PessoasJuridicasVinculadasField;
            }
            set {
                if ((object.ReferenceEquals(this.PessoasJuridicasVinculadasField, value) != true)) {
                    this.PessoasJuridicasVinculadasField = value;
                    this.RaisePropertyChanged("PessoasJuridicasVinculadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SemEmail {
            get {
                return this.SemEmailField;
            }
            set {
                if ((this.SemEmailField.Equals(value) != true)) {
                    this.SemEmailField = value;
                    this.RaisePropertyChanged("SemEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PessoaFisicaModel.PjVinculadaModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
        [System.SerializableAttribute()]
        public partial class PjVinculadaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CargoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CelularField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string DepartamentoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string EmailField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int IdPessoaJuridicaField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TelefoneField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Cargo {
                get {
                    return this.CargoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                        this.CargoField = value;
                        this.RaisePropertyChanged("Cargo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Celular {
                get {
                    return this.CelularField;
                }
                set {
                    if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                        this.CelularField = value;
                        this.RaisePropertyChanged("Celular");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Departamento {
                get {
                    return this.DepartamentoField;
                }
                set {
                    if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                        this.DepartamentoField = value;
                        this.RaisePropertyChanged("Departamento");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Email {
                get {
                    return this.EmailField;
                }
                set {
                    if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                        this.EmailField = value;
                        this.RaisePropertyChanged("Email");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int IdPessoaJuridica {
                get {
                    return this.IdPessoaJuridicaField;
                }
                set {
                    if ((this.IdPessoaJuridicaField.Equals(value) != true)) {
                        this.IdPessoaJuridicaField = value;
                        this.RaisePropertyChanged("IdPessoaJuridica");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Telefone {
                get {
                    return this.TelefoneField;
                }
                set {
                    if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                        this.TelefoneField = value;
                        this.RaisePropertyChanged("Telefone");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessRuleFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessUnauthorizedFault))]
    public partial class GenericFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessRuleFault", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class BusinessRuleFault : TesteExcelDna.RAE.WCF.Funcionario.GenericFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessUnauthorizedFault", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class BusinessUnauthorizedFault : TesteExcelDna.RAE.WCF.Funcionario.GenericFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingResultOfFuncionarioProdutoModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class PagingResultOfFuncionarioProdutoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel[] ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRegistrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel[] Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionarioProdutoModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class FuncionarioProdutoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAlteracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SituacaoFuncionarioProdutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAlteracao {
            get {
                return this.DataAlteracaoField;
            }
            set {
                if ((this.DataAlteracaoField.Equals(value) != true)) {
                    this.DataAlteracaoField = value;
                    this.RaisePropertyChanged("DataAlteracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SituacaoFuncionarioProduto {
            get {
                return this.SituacaoFuncionarioProdutoField;
            }
            set {
                if ((this.SituacaoFuncionarioProdutoField.Equals(value) != true)) {
                    this.SituacaoFuncionarioProdutoField = value;
                    this.RaisePropertyChanged("SituacaoFuncionarioProduto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingResultOfFuncionarioServicoModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class PagingResultOfFuncionarioServicoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel[] ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRegistrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel[] Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionarioServicoModel", Namespace="http://schemas.sebraesp.com.br/rae/v1/")]
    [System.SerializableAttribute()]
    public partial class FuncionarioServicoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAlteracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SituacaoFuncionarioServicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAlteracao {
            get {
                return this.DataAlteracaoField;
            }
            set {
                if ((this.DataAlteracaoField.Equals(value) != true)) {
                    this.DataAlteracaoField = value;
                    this.RaisePropertyChanged("DataAlteracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServico {
            get {
                return this.IdServicoField;
            }
            set {
                if ((this.IdServicoField.Equals(value) != true)) {
                    this.IdServicoField = value;
                    this.RaisePropertyChanged("IdServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SituacaoFuncionarioServico {
            get {
                return this.SituacaoFuncionarioServicoField;
            }
            set {
                if ((this.SituacaoFuncionarioServicoField.Equals(value) != true)) {
                    this.SituacaoFuncionarioServicoField = value;
                    this.RaisePropertyChanged("SituacaoFuncionarioServico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.sebraesp.com.br/rae/v1/", ConfigurationName="RAE.WCF.Funcionario.IFuncionario")]
    public interface IFuncionario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionario", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessUnauthorizedFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioBusinessUn" +
            "authorizedFaultFault", Name="BusinessUnauthorizedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioGenericFau" +
            "ltFault", Name="GenericFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessRuleFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioBusinessRu" +
            "leFaultFault", Name="BusinessRuleFault")]
        void CadastrarFuncionario(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel[] listaNovos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarios", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionariosGenericFault" +
            "Fault", Name="GenericFault")]
        TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel[] BuscarFuncionarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarCargos", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarCargosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarCargosGenericFaultFault", Name="GenericFault")]
        string[] BuscarCargos(int[] idFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncoes", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncoesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncoesGenericFaultFault" +
            "", Name="GenericFault")]
        string[] BuscarFuncoes(int[] idFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionariosPorLocal", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionariosPorLocalResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionariosPorLocalGene" +
            "ricFaultFault", Name="GenericFault")]
        TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel[] BuscarFuncionariosPorLocal(int[] idLocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarioProduto", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarioProdutoRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarioProdutoGeneri" +
            "cFaultFault", Name="GenericFault")]
        TesteExcelDna.RAE.WCF.Funcionario.PagingResultOfFuncionarioProdutoModel BuscarFuncionarioProduto(int[] idLocal, int[] IdFuncionario, int[] idProduto, string[] funcao, string[] cargo, int pagina, int tamanhoPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioProduto", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioProdutoRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioProdutoGen" +
            "ericFaultFault", Name="GenericFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessUnauthorizedFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioProdutoBus" +
            "inessUnauthorizedFaultFault", Name="BusinessUnauthorizedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessRuleFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioProdutoBus" +
            "inessRuleFaultFault", Name="BusinessRuleFault")]
        TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel CadastrarFuncionarioProduto(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioProduto", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioProdutoRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessRuleFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioProdutoBusin" +
            "essRuleFaultFault", Name="BusinessRuleFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioProdutoGener" +
            "icFaultFault", Name="GenericFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessUnauthorizedFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioProdutoBusin" +
            "essUnauthorizedFaultFault", Name="BusinessUnauthorizedFault")]
        TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel ExcluirFuncionarioProduto(int idFuncionario, int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarioServico", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarioServicoRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/BuscarFuncionarioServicoGeneri" +
            "cFaultFault", Name="GenericFault")]
        TesteExcelDna.RAE.WCF.Funcionario.PagingResultOfFuncionarioServicoModel BuscarFuncionarioServico(int[] idLocal, int[] IdFuncionario, int[] idServico, string[] funcao, string[] cargo, int pagina, int tamanhoPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioServico", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioServicoRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessRuleFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioServicoBus" +
            "inessRuleFaultFault", Name="BusinessRuleFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessUnauthorizedFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioServicoBus" +
            "inessUnauthorizedFaultFault", Name="BusinessUnauthorizedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/CadastrarFuncionarioServicoGen" +
            "ericFaultFault", Name="GenericFault")]
        TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel CadastrarFuncionarioServico(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioServico", ReplyAction="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioServicoRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.GenericFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioServicoGener" +
            "icFaultFault", Name="GenericFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessUnauthorizedFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioServicoBusin" +
            "essUnauthorizedFaultFault", Name="BusinessUnauthorizedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(TesteExcelDna.RAE.WCF.Funcionario.BusinessRuleFault), Action="http://schemas.sebraesp.com.br/rae/v1/IFuncionario/ExcluirFuncionarioServicoBusin" +
            "essRuleFaultFault", Name="BusinessRuleFault")]
        TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel ExcluirFuncionarioServico(int idFuncionario, int idServico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFuncionarioChannel : TesteExcelDna.RAE.WCF.Funcionario.IFuncionario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncionarioClient : System.ServiceModel.ClientBase<TesteExcelDna.RAE.WCF.Funcionario.IFuncionario>, TesteExcelDna.RAE.WCF.Funcionario.IFuncionario {
        
        public FuncionarioClient() {
        }
        
        public FuncionarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncionarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CadastrarFuncionario(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel[] listaNovos) {
            base.Channel.CadastrarFuncionario(listaNovos);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel[] BuscarFuncionarios() {
            return base.Channel.BuscarFuncionarios();
        }
        
        public string[] BuscarCargos(int[] idFuncionario) {
            return base.Channel.BuscarCargos(idFuncionario);
        }
        
        public string[] BuscarFuncoes(int[] idFuncionario) {
            return base.Channel.BuscarFuncoes(idFuncionario);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioModel[] BuscarFuncionariosPorLocal(int[] idLocal) {
            return base.Channel.BuscarFuncionariosPorLocal(idLocal);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.PagingResultOfFuncionarioProdutoModel BuscarFuncionarioProduto(int[] idLocal, int[] IdFuncionario, int[] idProduto, string[] funcao, string[] cargo, int pagina, int tamanhoPagina) {
            return base.Channel.BuscarFuncionarioProduto(idLocal, IdFuncionario, idProduto, funcao, cargo, pagina, tamanhoPagina);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel CadastrarFuncionarioProduto(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel model) {
            return base.Channel.CadastrarFuncionarioProduto(model);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioProdutoModel ExcluirFuncionarioProduto(int idFuncionario, int idProduto) {
            return base.Channel.ExcluirFuncionarioProduto(idFuncionario, idProduto);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.PagingResultOfFuncionarioServicoModel BuscarFuncionarioServico(int[] idLocal, int[] IdFuncionario, int[] idServico, string[] funcao, string[] cargo, int pagina, int tamanhoPagina) {
            return base.Channel.BuscarFuncionarioServico(idLocal, IdFuncionario, idServico, funcao, cargo, pagina, tamanhoPagina);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel CadastrarFuncionarioServico(TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel model) {
            return base.Channel.CadastrarFuncionarioServico(model);
        }
        
        public TesteExcelDna.RAE.WCF.Funcionario.FuncionarioServicoModel ExcluirFuncionarioServico(int idFuncionario, int idServico) {
            return base.Channel.ExcluirFuncionarioServico(idFuncionario, idServico);
        }
    }
}
